# Generated by Django 4.0.5 on 2023-07-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicandband', '0002_alter_musicandband_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicandBand',
            new_name='MusicandBand1',
        ),
    ]
