# Generated by Django 4.0.5 on 2023-07-31 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('musicandband', '0004_musicandband'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicandband',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
